# first print

In [9]:
print("First Print in Python")

First Print in Python

In [10]:
# print my name 
print ("Saad Rimeh")

Saad Rimeh

# Data Type

In [11]:
type(2)

int

In [12]:
type(2.5)

float

In [13]:
type('s')

str

In [14]:
type("saad")

str

In [16]:
type(True)

bool

In [17]:
type(False)

bool

## OP

In [18]:
1+2

3

In [19]:
2.4+2

4.4

In [20]:
2*2

4

In [21]:
2/2

1.0

In [22]:
2%2

0

# String Method

In [23]:
"saad rimeh".upper()

'SAAD RIMEH'

In [24]:
"Saad Rimeh".lower()

'saad rimeh'

In [25]:
"title".title()

'Title'

In [27]:
# here will print the last method in the cell but if we have a print they will run all of it
"saad rimeh".upper()
"Saad Rimeh".lower()
"title".title()

'Title'

In [29]:
# count how many a in the string
"saad rimeh".count('a')

2

In [31]:
# A != a
"saad rimeh".count('A')

0

In [34]:
# replace a with A
"saad rimeh".replace('a','A')

'sAAd rimeh'

# Variables

In [35]:
# A variable is a named container in a program's memory used to store data that can be referenced, used, or changed later.

In [2]:
message_1 = "I am learning Python "

In [3]:
# To output the value of a variable, simply pass its name to the print function
message_1

'I am learning Python '

In [5]:
message_2 = "and it is fun!"

In [6]:
message_2

'and it is fun!'

In [40]:
message_1

'I am learning Python'

In [42]:
# it will run onle the last line
message_1
message_2

'and it is fun!'

In [44]:
message_1 + message_2

'I am learning Pythonand it is fun!'

In [7]:
message_1 + message_2

'I am learning Python and it is fun!'

In [8]:
# if we not put space in the last of message_1 the output will be I am learning Pythonand it is fun!
# we can write like this message_1 + " " + message_2 but it not professional

In [9]:
message = message_1 + message_2
message

'I am learning Python and it is fun!'

In [10]:
f'Hello World'

'Hello World'

In [11]:
f'{message_1}{message_2}'

'I am learning Python and it is fun!'

In [12]:
# if we but abs btween {}{} the output will be I am learning Python abcand it is fun!
f'{message_1}abc{message_2}'

'I am learning Python abcand it is fun!'

# List

In [13]:
# A list is an ordered and changeable data structure used to store a collection of multiple items within a single variable.

In [11]:
countries=['Japan' , 'Brazil' , 'Canada' , 'Australia' , 'Egypt']

In [12]:
countries

['Japan', 'Brazil', 'Canada', 'Australia', 'Egypt']

In [13]:
# List mabye contain more than one data type

In [14]:
# Access a specific element by its index, keeping in mind that the first index is always 0

In [15]:
countries [0]

'Japan'

In [16]:
countries [1]

'Brazil'

In [17]:
countries [2]

'Canada'

In [18]:
countries [3]

'Australia'

In [19]:
countries [4]

'Egypt'

In [20]:
# the length of the countries list is 4 if we write countries [5] the output will be IndexError: list index out of range

In [21]:
# Use negative indexing to access elements from the end of the list, where -1 refers to the last item

In [22]:
countries [-1]

'Egypt'

In [23]:
countries [-2]

'Australia'

In [24]:
countries [-3]

'Canada'

In [25]:
countries [-4]

'Brazil'

In [26]:
# Use slicing to extract a portion of a list by specifying a start and stop index [start:stop]

In [27]:
# it stope on number 3 so it print untile 2
countries [0:3]

['Japan', 'Brazil', 'Canada']

## Adding elements to a list

In [28]:
countries

['Japan', 'Brazil', 'Canada', 'Australia', 'Egypt']

In [29]:
# add element at the end of list
countries.append('Syria')

In [30]:
countries

['Japan', 'Brazil', 'Canada', 'Australia', 'Egypt', 'Syria']

In [31]:
# add element at the first fo list
countries.insert(0,'spain')

In [32]:
countries

['spain', 'Japan', 'Brazil', 'Canada', 'Australia', 'Egypt', 'Syria']

In [33]:
countries_2 = ['UK' , 'Germany']

In [34]:
countries + countries_2

['spain',
 'Japan',
 'Brazil',
 'Canada',
 'Australia',
 'Egypt',
 'Syria',
 'UK',
 'Germany']

In [35]:
nested_list = [countries_2 ,countries]

In [36]:
nested_list

[['UK', 'Germany'],
 ['spain', 'Japan', 'Brazil', 'Canada', 'Australia', 'Egypt', 'Syria']]

In [37]:
countries_2.insert(0,countries)

In [38]:
countries_2

[['spain', 'Japan', 'Brazil', 'Canada', 'Australia', 'Egypt', 'Syria'],
 'UK',
 'Germany']

## Removing an elements

In [39]:
# remove the elment from the lsit
countries.remove("Syria")

In [40]:
countries

['spain', 'Japan', 'Brazil', 'Canada', 'Australia', 'Egypt']

In [41]:
# removing with index using pop
countries.pop(-1)

'Egypt'

In [42]:
# pop remove the element on the index and returne the elemet

In [43]:
del countries [0]

In [44]:
countries

['Japan', 'Brazil', 'Canada', 'Australia']

In [45]:
#The key difference is that pop() removes an item and returns its value so you can use it, whereas del simply deletes the item without returning anything.

## Sorting a list

In [46]:
numbers = [ 5 , 2 , 7 , 1 ,9 ,10 , 6 , 0 ]

In [47]:
# defulte from small to lage
numbers.sort()

In [48]:
numbers

[0, 1, 2, 5, 6, 7, 9, 10]

In [49]:
# Set reverse=True to sort the list in descending order (from highest to lowest)

In [50]:
numbers = [ 5 , 2 , 7 , 1 ,9 ,10 , 6 , 0 ]
numbers.sort(reverse=True)

In [51]:
numbers

[10, 9, 7, 6, 5, 2, 1, 0]

## Update an element

In [52]:
numbers [0] = 1000
numbers

[1000, 9, 7, 6, 5, 2, 1, 0]

## Copying a list

In [54]:
countries [:]

['Japan', 'Brazil', 'Canada', 'Australia']

In [55]:
new_list = countries[:]

In [56]:
new_list

['Japan', 'Brazil', 'Canada', 'Australia']

In [57]:
countries.copy()

['Japan', 'Brazil', 'Canada', 'Australia']

In [58]:
new_list_2 = countries.copy()

In [59]:
new_list_2

['Japan', 'Brazil', 'Canada', 'Australia']

# Dictionary

In [60]:
# A Python dictionary is a collection of key-value pairs used to store data values

In [61]:
my_dict = {'key1':'value1' , 'key2':'value2'}

In [62]:
my_dict

{'key1': 'value1', 'key2': 'value2'}

In [63]:
#a Python dictionary is very similar to a standard JavaScript object. Both are data structures used to store information in key-value pairs using curly braces {}.

In [65]:
my_dict_2 = {
    'user1': {'name': 'saad', 'lastName': 'Rimeh'},
    'user2': {'name': 'Ali', 'lastName': 'Rimeh'}
}

In [66]:
my_dict_2

{'user1': {'name': 'saad', 'lastName': 'Rimeh'},
 'user2': {'name': 'Ali', 'lastName': 'Rimeh'}}

In [70]:
my_dict_2['user1']['name']

'saad'

In [71]:
my_dict_2.keys()

dict_keys(['user1', 'user2'])

In [73]:
my_dict_2.values()

dict_values([{'name': 'saad', 'lastName': 'Rimeh'}, {'name': 'Ali', 'lastName': 'Rimeh'}])

In [74]:
my_data={'name':'saad', 'age':25}

In [76]:
my_data.keys()

dict_keys(['name', 'age'])

In [77]:
my_data.values()

dict_values(['saad', 25])

In [78]:
my_data.items()

dict_items([('name', 'saad'), ('age', 25)])

In [79]:
my_data['height']=1.7

In [80]:
my_data

{'name': 'saad', 'age': 25, 'height': 1.7}

In [81]:
my_data.update({'height': 1.8})

In [82]:
my_data

{'name': 'saad', 'age': 25, 'height': 1.8}

## Copy a dictionary

In [83]:
my_data.copy()

{'name': 'saad', 'age': 25, 'height': 1.8}

In [84]:
new_dict=my_data.copy()
# if we update the old dic this will not change 
new_dict

{'name': 'saad', 'age': 25, 'height': 1.8}

In [85]:
# if we want to chage the copy when we change the old dict

In [86]:
new_dict_2= my_data

In [87]:
new_dict_2

{'name': 'saad', 'age': 25, 'height': 1.8}

## Remove Element

In [88]:
my_data.pop('height')

1.8

In [89]:
my_data

{'name': 'saad', 'age': 25}

In [90]:
del my_data ['age']

In [91]:
my_data

{'name': 'saad'}

In [92]:
# clear all of item 
my_data.clear()

In [93]:
my_data

{}

# If Statement

if <condition>:
  <code>
elif <condition>:
  <code>
...
else:
  <code>

In [94]:
# do not forget the space in if statment and else if

In [102]:
age = 15

In [103]:
if age >= 18:
    print("You're an adult! ")
elif age>=13:
    print("You're a teenager")
else:
    print("You're a kid")

You're a teenager

# For loop

for <variable> in <list>:
  <code>

In [104]:
countries

['Japan', 'Brazil', 'Canada', 'Australia']

In [105]:
for country in countries:
    print(country)

Japan
Brazil
Canada
Australia

In [107]:
#enumerate() is a built-in Python function that adds an automatic counter to a collection, returning each item alongside its index as a tuple (e.g., (0, 'japan')).

In [108]:
for country in enumerate (countries):
    print(country)

(0, 'Japan')
(1, 'Brazil')
(2, 'Canada')
(3, 'Australia')

In [114]:
for i ,country in enumerate (countries):
    print(i)
    print(country)

0
Japan
1
Brazil
2
Canada
3
Australia

In [115]:
my_data

{}

In [116]:
my_data={'name': 'saad' , 'age':25}

In [117]:
my_data

{'name': 'saad', 'age': 25}

In [118]:
for key , value in my_data.items():
    print(key)
    print(value)

name
saad
age
25

# Function

def function (<params>):
    <code>
    return <data>

In Python, a function is a reusable block of code defined with the def keyword that runs only when you call it. It allows you to pass data in as arguments, perform a specific task, and return a result, which keeps your code organized and prevents repetition.

In [120]:
def sum_values (a , b):
    x=a + b
    return x

In [122]:
# 5 = a , 8 = b
sum_values(5 , 8)

13

## Built-in Functions

Built-in functions in Python are pre-written, ready-to-use tools built directly into the language, meaning you can use them instantly without having 
to import any external files or libraries.

In [124]:
countries = ['Japan' , 'Brazil' , 'Canada' , 'Australia' , 'Egypt']

In [125]:
len(countries)

5

In [126]:
max([10 , 5 , 65 , 99 , 50 , 30])

99

In [127]:
min([10 , 5 , 65 , 99 , 50 , 30])

5

In [130]:
range(1 , 10 ,2)

range(1, 10, 2)

In [132]:
for i in  range(1 , 10 ,2):
  print(i)

1
3
5
7
9

# Module

In Python, a module is simply a file containing Python code (like functions, variables, or classes) that you can bring into your current project using the import keyword, allowing you to organize and reuse your code easily.

import

## OS Module

In [135]:
import os

os.getcwd() stands for "Get Current Working Directory." It is a function from the os module that returns the exact file path of the folder where your Python script is currently running.

In [137]:
os.getcwd()

'C:\\Users\\Windows.11\\Data_Analyse'

os.listdir() is a function from the os module that returns a list of all the file and folder names inside a specific directory. If you leave the parentheses empty, it shows everything in your current working directory.

In [139]:
os.listdir()

['.git', '.ipynb_checkpoints', 'Example.ipynb']

os.makedirs("New Folder") is a function from the os module that creates a new directory (folder) named "New Folder" in your current working directory. It is especially powerful because it can create multiple nested folders all at once if you give it a longer path (like os.makedirs("project/data/images")).

In [140]:
os.makedirs("New Folder")

In [141]:
os.listdir()

['.git', '.ipynb_checkpoints', 'Example.ipynb', 'New Folder']

# Creating a dataframe from an array

## Optin 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
# creating an array
data = np.array([[1, 4] ,[2 , 5],[3,6]])

In [3]:
data

array([[1, 4],
       [2, 5],
       [3, 6]])

This code uses the pandas library to create a structured data table (called a DataFrame) named df using existing data, while assigning custom names to its three rows (index) and two columns (columns).

In [4]:
# creating a dataframe
df=pd.DataFrame(data , index=['row1' ,'row2' , 'row3'] , 
            columns=['col1' , 'col2'])

In [5]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

## Option 2

In [6]:
# creating an array with list shape
data = [[1, 4] ,[2 , 5],[3,6]]

In [7]:
# creating a Dataframe
df=pd.DataFrame(data , index=['row1' ,'row2' , 'row3'] , 
            columns=['col1' , 'col2'])

In [8]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# Creating DataFrame from a dictionary

In [9]:
# lists used for this example
states = ['California' , 'Texas' , 'Florida' , 'New York']
population = [365201 , 102102 , 219445 , 4585685]

In [10]:
# Storing lists within a dictionart
dict_states = {'States': states , 'populatin':population}

In [11]:
# Creating the dataFrame
df_population = pd.DataFrame(dict_states)

In [12]:
# Showing the dataframe
df_population

       States  populatin
0  California     365201
1       Texas     102102
2     Florida     219445
3    New York    4585685

# Creating a DataFrame From a csv file

In [13]:
# reading the csv file 
df_exam = pd.read_csv('testcsv2.CSV', encoding='windows-1256')

In [17]:
df_exam.head()

,تفاصيل,الرقم,الاسم,العنوان,هاتف,خط السير,مكان العمل,الرصيد
0,,3581,اسواق الامين,حي الشهداء قرب جامع جامع التقوى,7.822114e+09,"الخميس,","33.332153, 43.784812",0
1,,3617,06أسواق اليمامه / (براد الشركة),الفلوجة حي الشهداء شارع علي النجيه,7.714468e+09,"الخميس,","33.3311934,43.7923167",0
2,,4856,02مركز الباشا للتسوق / (براد الشركة),الفلوجة حي الشهداء شارع المنجزات,7.727010e+09,"الخميس,","33.332160, 43.784696",0
3,,6348,05اسواق مازن \ (براد شركة),اقرب نقطة دالة جامع المرسيلين,7.806842e+09,"الخميس,","33.332442, 43.796743",0
4,,6535,06مركز هيا التسوق / (براد شركة),حي شهداء قرب جامع الشمري,7.904385e+09,"الخميس,","33.329548, 43.792596",0

This section successfully loads the Arabic CSV file by applying the windows-1256 encoding to prevent decoding errors. It also uses the df.head() function, which defaults to showing only the first 5 rows of the DataFrame to provide a quick, lightweight preview of the data.

In [16]:
# the CSV shoulde be located on the root of the py

In [18]:
df_exam

,تفاصيل,الرقم,الاسم,العنوان,هاتف,خط السير,مكان العمل,الرصيد
0,,3581,اسواق الامين,حي الشهداء قرب جامع جامع التقوى,7.822114e+09,"الخميس,","33.332153, 43.784812",0
1,,3617,06أسواق اليمامه / (براد الشركة),الفلوجة حي الشهداء شارع علي النجيه,7.714468e+09,"الخميس,","33.3311934,43.7923167",0
2,,4856,02مركز الباشا للتسوق / (براد الشركة),الفلوجة حي الشهداء شارع المنجزات,7.727010e+09,"الخميس,","33.332160, 43.784696",0
3,,6348,05اسواق مازن \ (براد شركة),اقرب نقطة دالة جامع المرسيلين,7.806842e+09,"الخميس,","33.332442, 43.796743",0
4,,6535,06مركز هيا التسوق / (براد شركة),حي شهداء قرب جامع الشمري,7.904385e+09,"الخميس,","33.329548, 43.792596",0
5,,7215,06اسواق الطارق \ (براد شركة),الفلوجه منطقة الشهداء,7.838347e+09,"الخميس,","33.327072, 43.785803",0
6,,7279,07اسواق أبو سلطان للتسوق \ (براد شركة),فلوجه جبيل,7.822052e+09,"الخميس,","33.325670, 43.783278",0
7,,7406,04ماركت الخليج للتسوق (براد الشركة),للتسوق الفلوجه الشهداء,7.843495e+09,"الخميس,","33.329230, 43.785996",0
8,,7476,07سوبر ماركت ابن الفلوجة(براد شركة),الفلوجة - حي الشهداء قرب مصلى وبالوالدين احسانا,7.519382e+09,"الخميس,","33.328534, 43.792461",0
9,,7774,05ماركت النايل (براد شركة),الفلوجة حي الشهداء قرب أسواق البركة,7.822847e+09,"الخميس,","33.328322, 43.785718",0
10,,7819,04ماركت اليرموك (براد شركة),الفلوجة حي الشهداء شارع الشمري,7.817948e+09,"الخميس,","33.335115, 43.795579",0
11,,8307,08اسواق المشهداني (براد شركة),الفلوجه جبيل,7.858804e+09,"الخميس,","33.327626, 43.778113",0
12,,8324,06اسواق النحل (براد الشركة),الفلوجه جبيل,7.838414e+09,"الخميس,","33.327728, 43.780699",0
13,,8967,اسواق بغداد (براد شركة),الفلوجه الشهداء,7.805800e+09,"الخميس,","33.335008, 43.794713",0
14,,9063,اسواق وجدي مول (براد شركة),منطقه الفلوجه شارع المنجزات قرب مرطبات مشمشه,7.814985e+09,"الخميس,","33.330149, 43.785658",0
15,,9139,اسواق الرحمن (براد شركة),منطقه الشهداء شارع علي نجيه قرب جامع الشمري,7.741178e+09,"الخميس,","33.330857, 43.792342",0
16,,9233,اسواق وضاح (براد شركة),منطقه الشهداء قرب مدرسه المفاخر,7.886203e+09,"الخميس,","33.330552, 43.787290",0
17,,9311,أسواق البركة (براد شركة),منطقة الشهداء قرب جامع التقوى,7.804702e+09,"الخميس,","33.332527, 43.792123",0
18,,9407,أسواق الرحاب 1 (براد شركة),منطقة جبيل مقابل مجمع الرحاب,7.731893e+09,"الخميس,","33.325661, 43.784960",0
19,,9426,ماركت الكرم (براد شركة),منطقة الشهداء قرب مدرسة المفاخر,7.800160e+09,"الخميس,","33.330789, 43.787937",0
20,,9445,اسواق الملكي (براد شركة),منطقة جبيل قرب جامع جعفر,7.837121e+09,"الخميس,","33.327804, 43.783515",0
21,NaN,21,NaN,NaN,NaN,NaN,NaN,0

In [19]:
# show last 5 rows in a dataframe
df_exam.tail()

,تفاصيل,الرقم,الاسم,العنوان,هاتف,خط السير,مكان العمل,الرصيد
17,,9311,أسواق البركة (براد شركة),منطقة الشهداء قرب جامع التقوى,7.804702e+09,"الخميس,","33.332527, 43.792123",0
18,,9407,أسواق الرحاب 1 (براد شركة),منطقة جبيل مقابل مجمع الرحاب,7.731893e+09,"الخميس,","33.325661, 43.784960",0
19,,9426,ماركت الكرم (براد شركة),منطقة الشهداء قرب مدرسة المفاخر,7.800160e+09,"الخميس,","33.330789, 43.787937",0
20,,9445,اسواق الملكي (براد شركة),منطقة جبيل قرب جامع جعفر,7.837121e+09,"الخميس,","33.327804, 43.783515",0
21,NaN,21,NaN,NaN,NaN,NaN,NaN,0

In [20]:
# show first 10 rows
df_exam.head(10)

,تفاصيل,الرقم,الاسم,العنوان,هاتف,خط السير,مكان العمل,الرصيد
0,,3581,اسواق الامين,حي الشهداء قرب جامع جامع التقوى,7.822114e+09,"الخميس,","33.332153, 43.784812",0
1,,3617,06أسواق اليمامه / (براد الشركة),الفلوجة حي الشهداء شارع علي النجيه,7.714468e+09,"الخميس,","33.3311934,43.7923167",0
2,,4856,02مركز الباشا للتسوق / (براد الشركة),الفلوجة حي الشهداء شارع المنجزات,7.727010e+09,"الخميس,","33.332160, 43.784696",0
3,,6348,05اسواق مازن \ (براد شركة),اقرب نقطة دالة جامع المرسيلين,7.806842e+09,"الخميس,","33.332442, 43.796743",0
4,,6535,06مركز هيا التسوق / (براد شركة),حي شهداء قرب جامع الشمري,7.904385e+09,"الخميس,","33.329548, 43.792596",0
5,,7215,06اسواق الطارق \ (براد شركة),الفلوجه منطقة الشهداء,7.838347e+09,"الخميس,","33.327072, 43.785803",0
6,,7279,07اسواق أبو سلطان للتسوق \ (براد شركة),فلوجه جبيل,7.822052e+09,"الخميس,","33.325670, 43.783278",0
7,,7406,04ماركت الخليج للتسوق (براد الشركة),للتسوق الفلوجه الشهداء,7.843495e+09,"الخميس,","33.329230, 43.785996",0
8,,7476,07سوبر ماركت ابن الفلوجة(براد شركة),الفلوجة - حي الشهداء قرب مصلى وبالوالدين احسانا,7.519382e+09,"الخميس,","33.328534, 43.792461",0
9,,7774,05ماركت النايل (براد شركة),الفلوجة حي الشهداء قرب أسواق البركة,7.822847e+09,"الخميس,","33.328322, 43.785718",0

In [21]:
# show last 10 rwos
df_exam.tail(10)

,تفاصيل,الرقم,الاسم,العنوان,هاتف,خط السير,مكان العمل,الرصيد
12,,8324,06اسواق النحل (براد الشركة),الفلوجه جبيل,7.838414e+09,"الخميس,","33.327728, 43.780699",0
13,,8967,اسواق بغداد (براد شركة),الفلوجه الشهداء,7.805800e+09,"الخميس,","33.335008, 43.794713",0
14,,9063,اسواق وجدي مول (براد شركة),منطقه الفلوجه شارع المنجزات قرب مرطبات مشمشه,7.814985e+09,"الخميس,","33.330149, 43.785658",0
15,,9139,اسواق الرحمن (براد شركة),منطقه الشهداء شارع علي نجيه قرب جامع الشمري,7.741178e+09,"الخميس,","33.330857, 43.792342",0
16,,9233,اسواق وضاح (براد شركة),منطقه الشهداء قرب مدرسه المفاخر,7.886203e+09,"الخميس,","33.330552, 43.787290",0
17,,9311,أسواق البركة (براد شركة),منطقة الشهداء قرب جامع التقوى,7.804702e+09,"الخميس,","33.332527, 43.792123",0
18,,9407,أسواق الرحاب 1 (براد شركة),منطقة جبيل مقابل مجمع الرحاب,7.731893e+09,"الخميس,","33.325661, 43.784960",0
19,,9426,ماركت الكرم (براد شركة),منطقة الشهداء قرب مدرسة المفاخر,7.800160e+09,"الخميس,","33.330789, 43.787937",0
20,,9445,اسواق الملكي (براد شركة),منطقة جبيل قرب جامع جعفر,7.837121e+09,"الخميس,","33.327804, 43.783515",0
21,NaN,21,NaN,NaN,NaN,NaN,NaN,0

In [22]:
# getting access to the shape attribute
df_exam.shape

(22, 8)

In [23]:
# display n rows
pd.set_option('display.max_rows',22)
df_exam

,تفاصيل,الرقم,الاسم,العنوان,هاتف,خط السير,مكان العمل,الرصيد
0,,3581,اسواق الامين,حي الشهداء قرب جامع جامع التقوى,7.822114e+09,"الخميس,","33.332153, 43.784812",0
1,,3617,06أسواق اليمامه / (براد الشركة),الفلوجة حي الشهداء شارع علي النجيه,7.714468e+09,"الخميس,","33.3311934,43.7923167",0
2,,4856,02مركز الباشا للتسوق / (براد الشركة),الفلوجة حي الشهداء شارع المنجزات,7.727010e+09,"الخميس,","33.332160, 43.784696",0
3,,6348,05اسواق مازن \ (براد شركة),اقرب نقطة دالة جامع المرسيلين,7.806842e+09,"الخميس,","33.332442, 43.796743",0
4,,6535,06مركز هيا التسوق / (براد شركة),حي شهداء قرب جامع الشمري,7.904385e+09,"الخميس,","33.329548, 43.792596",0
5,,7215,06اسواق الطارق \ (براد شركة),الفلوجه منطقة الشهداء,7.838347e+09,"الخميس,","33.327072, 43.785803",0
6,,7279,07اسواق أبو سلطان للتسوق \ (براد شركة),فلوجه جبيل,7.822052e+09,"الخميس,","33.325670, 43.783278",0
7,,7406,04ماركت الخليج للتسوق (براد الشركة),للتسوق الفلوجه الشهداء,7.843495e+09,"الخميس,","33.329230, 43.785996",0
8,,7476,07سوبر ماركت ابن الفلوجة(براد شركة),الفلوجة - حي الشهداء قرب مصلى وبالوالدين احسانا,7.519382e+09,"الخميس,","33.328534, 43.792461",0
9,,7774,05ماركت النايل (براد شركة),الفلوجة حي الشهداء قرب أسواق البركة,7.822847e+09,"الخميس,","33.328322, 43.785718",0
10,,7819,04ماركت اليرموك (براد شركة),الفلوجة حي الشهداء شارع الشمري,7.817948e+09,"الخميس,","33.335115, 43.795579",0
11,,8307,08اسواق المشهداني (براد شركة),الفلوجه جبيل,7.858804e+09,"الخميس,","33.327626, 43.778113",0
12,,8324,06اسواق النحل (براد الشركة),الفلوجه جبيل,7.838414e+09,"الخميس,","33.327728, 43.780699",0
13,,8967,اسواق بغداد (براد شركة),الفلوجه الشهداء,7.805800e+09,"الخميس,","33.335008, 43.794713",0
14,,9063,اسواق وجدي مول (براد شركة),منطقه الفلوجه شارع المنجزات قرب مرطبات مشمشه,7.814985e+09,"الخميس,","33.330149, 43.785658",0
15,,9139,اسواق الرحمن (براد شركة),منطقه الشهداء شارع علي نجيه قرب جامع الشمري,7.741178e+09,"الخميس,","33.330857, 43.792342",0
16,,9233,اسواق وضاح (براد شركة),منطقه الشهداء قرب مدرسه المفاخر,7.886203e+09,"الخميس,","33.330552, 43.787290",0
17,,9311,أسواق البركة (براد شركة),منطقة الشهداء قرب جامع التقوى,7.804702e+09,"الخميس,","33.332527, 43.792123",0
18,,9407,أسواق الرحاب 1 (براد شركة),منطقة جبيل مقابل مجمع الرحاب,7.731893e+09,"الخميس,","33.325661, 43.784960",0
19,,9426,ماركت الكرم (براد شركة),منطقة الشهداء قرب مدرسة المفاخر,7.800160e+09,"الخميس,","33.330789, 43.787937",0
20,,9445,اسواق الملكي (براد شركة),منطقة جبيل قرب جامع جعفر,7.837121e+09,"الخميس,","33.327804, 43.783515",0
21,NaN,21,NaN,NaN,NaN,NaN,NaN,0

In [24]:
import pandas as pd

In [25]:
# reading the scv file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [26]:
# showing the dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## Attributes

In [27]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [28]:
# getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [30]:
# Getting access to the colum attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [31]:
# data types of each colums
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

## Methods

In [36]:
# Showing the first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [37]:
# Showing the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [41]:
# describing basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## Functions

In [48]:
# obtaining the length of the dataframe (number of rows)
len(df_exams)

1000

In [50]:
# obtaining the highest index of the dataframe
max(df_exams.index)

999

In [51]:
# obtaining the lowest index of the dataframe
min(df_exams.index)

0

In [52]:
# obtaining the data type
type(df_exams)

pandas.core.frame.DataFrame

In [53]:
# Rounding the values of the dataset
round(df_exams , 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [54]:
# This tells Pandas not to limit the maximum number of rows displayed
pd.set_option('display.max_rows', None)

# Now when you call the dataframe, it will print all 1000 rows
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# Selecting one column

## Syntax 1

In [58]:
import pandas as pd
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [65]:
# select a column with [] (preferred way to select a column)
df_exams['gender'].head().describe()

count          5
unique         2
top       female
freq           3
Name: gender, dtype: object

In [66]:
# check out the data type of a column
type(df_exams['gender'])

pandas.core.series.Series

In [67]:
# series: attributes and methods
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

## Syntax 2

In [72]:
# select a column with .
df_exams.gender.head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [78]:
# Select a column with . (pitfalls)
#we can use it if the column name have more than 1 world
df_exams.math_score

AttributeError: 'DataFrame' object has no attribute 'math_score'

In [79]:
# select the same column using []
df_exams['math score'].head()

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

# Selecting two or more columns

In [80]:
import pandas as pd

In [81]:
df_exams=pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [89]:
# selsect 2 columns using [[]]
df_exams[['gender' , 'math score']].head().describe()

       math score
count    5.000000
mean    70.800000
std     15.546704
min     47.000000
25%     69.000000
50%     72.000000
75%     76.000000
max     90.000000

In [101]:
df_exams[['gender' , 'math score']].head()

   gender  math score
0  female          72
1  female          69
2  female          90
3    male          47
4    male          76

In [102]:
# check out the data type of the selection
type(df_exams[['gender' , 'math score']])

pandas.core.frame.DataFrame

In [103]:
# select 2 or more columns using [[]]
df_exams[['gender' , 'math score' , 'reading score' , 'writing score']].head()

   gender  math score  reading score  writing score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [ ]:
# we can not select 2 columns with the "."